version: '3.8'

services:
  calculator-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    volumes:
      # Optional: mount source code for development
      # - .:/app
      # - /app/.venv  # Exclude virtual environment
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 